# version: '3.8'

networks:
  events:
    driver: bridge

services:
  # postgres:
  #   container_name: postgres
  #   image: postgres:latest
  #   restart: always
  #   environment:
  #     POSTGRES_DB: events
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 1
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #    - events

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    environment:
      REDIS_PASSWORD: 1
    ports:
      - 6379:6379
    networks:
      - events

volumes:
  postgres-data:
